@startmindmap
!theme amiga
<style>
mindmapDiagram {
  .wdio{
    BackgroundColor orange
  }
  .who {
    BackgroundColor lightgreen
  }
  .what {
    BackgroundColor #FFBBCC
  }
  .where {
    BackgroundColor gold
  }
  .when {
    BackgroundColor brown
  }
  .why {
    BackgroundColor lightblue
  }

}
</style>
* **PS-WDIO** Capabilities <<wdio>>
right side
** actors<<who>>
*** developers
**** unit testing
*** quality engrs
**** integration test
**** regression testing
**** e2e testing
**** tool ownership
**** test suite\n management
** repository <<where>>
*** github
*** monorepo
*** product agnostic
** continous testing<<when>>
*** github actions
*** scheduled testing
left side
** services<<what>>
*** web-standalone
**** web driver
*** app-standalone
**** appium
**** ios *mac only 
**** android
**** emulators
*** api
*** platforms
**** web automate
***** cross-browser testing
**** app automate
***** cross-device testing
** test executions <<what>>
*** unit test
*** integration test
*** regression testing
*** e2e testing
*** test suite\n configurations
** readability
*** page object\n model
*** BDD approach?
*** unified or \n common test

@endmindmap